### PR TITLE
added walk commands to banni

### PR DESCRIPTION
**Pull request by Etothepowerof26**
+walk
-walk

probably will get added by wicopee before we are able to look at the commit
but eh its worth a shot

### CODE REVIEW

**Comment by Etothepowerof26** [comment]
might be too many walks

**Comment by ghost** [comment]
Please, put descriptive pull request titles.

**Comment by Etothepowerof26** [comment]
so it cant be just an update

**Comment by ghost** [comment]
And if I mean decriptive pull request titles, I mean something like this:  `Added *insert new feature here*`.

**Comment by Etothepowerof26** [comment]
so something like this

**Comment by ghost** [comment]
The slow speed is already added there, plus you can break this feature by typing in console `-walk`.

**Comment by Etothepowerof26** [comment]
wait what

**Comment by ghost** [comment]
`ply:SetRunSpeed(ply:GetWalkSpeed())`

**Pull request closed without merging**
