### PR TITLE
garryclicker - client sided clicker game

### PR DESCRIPTION
**Pull request by Etothepowerof26**
i have worked on 2 versions of this:
legacy version is around 910 lines, this is around 553
i saved around 400 lines by changing table formats

hope this works

### CODE REVIEW

**Comment by Etothepowerof26** [comment]
dont mind that conversation

**Comment by Tenrys** [comment]
It says that because the commit is part of a pull request to this repository, I guess. are you done?

**Comment by Etothepowerof26** [comment]
well i mean
i just got done with it yesterday
so i can update the lua script

**Comment by Tenrys** [comment]
I don't know if this is necessary honestly

**Comment by Etothepowerof26** [comment]
meh

**Pull request closed without merging**
